[features]
seeds = false
skip-lint = false

[programs.devnet]
solotery = "Caj6vkJqXNP5rKVkQin3QPecjvZSoyujNUd5HvGmxVGX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mateo/.config/solana/id.json"

[scripts]
create = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/createLotery.ts"
request = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/requestTicket.ts"
